
name: Run Selenium On GitHub Action
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install Selenium
        run: pip install selenium

      - name: Setup Docker Compose
        run: docker-compose -f docker-compose.yaml up -d

      - name: Give Write Access to Wait for Grid Script
        run: chmod +x wait-for-grid.sh

      - name: Wait for grid
        run: ./wait-for-grid.sh
      
      - name: Running the Python file
        run: python3 test_uts_chinese_website.py

      - name: Setdown Docker Compose
        run: docker-compose -f docker-compose.yaml down

